// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "go-swagger",
            "url": "https://github.com/hktalent/"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/rsc": {
            "post": {
                "description": "保存连接信息,保存api,GORM V2 将使用 upsert 来保存关联记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "remoute",
                    "server",
                    "config"
                ],
                "summary": "保存ssh、vnc、rdp等远程连接配置信息",
                "responses": {}
            }
        },
        "/api/v1/rsc/:ip/:port": {
            "post": {
                "description": "通过ip、port返回连接信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "remoute",
                    "server",
                    "config"
                ],
                "summary": "通过ip、port返回连接信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ip address",
                        "name": "ip",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "port",
                        "name": "port",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "51pwn app API",
	Description:      "This is 51pwn app api docs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
